edges:
- cost: 1.84
  from: node_00
  to: node_01
- cost: 1.84
  from: node_01
  to: node_00
- cost: 2.79
  from: node_00
  to: node_02
- cost: 2.79
  from: node_02
  to: node_00
- cost: 1.71
  from: node_00
  to: node_04
- cost: 1.71
  from: node_04
  to: node_00
- cost: 1.83
  from: node_00
  to: node_05
- cost: 1.83
  from: node_05
  to: node_00
- cost: 1.86
  from: node_01
  to: node_02
- cost: 1.86
  from: node_02
  to: node_01
- cost: 2.32
  from: node_01
  to: node_04
- cost: 2.32
  from: node_04
  to: node_01
- cost: 1.88
  from: node_02
  to: node_03
- cost: 1.88
  from: node_03
  to: node_02
- cost: 1.86
  from: node_02
  to: node_04
- cost: 1.86
  from: node_04
  to: node_02
- cost: 2.36
  from: node_03
  to: node_04
- cost: 2.36
  from: node_04
  to: node_03
- cost: 2.34
  from: node_04
  to: node_05
- cost: 2.34
  from: node_05
  to: node_04
nodes:
- id: node_00
  tags:
  - site1
  x: 1.912
  y: 1.396
  yaw: 0.778
- id: node_01
  tags:
  - site2
  x: 3.199
  y: 2.704
  yaw: 1.602
- id: node_02
  tags:
  - site3
  x: 2.074
  y: 4.184
  yaw: 2.35
- id: node_03
  tags:
  - site4
  x: 0.42
  y: 5.076
  yaw: -1.577
- id: node_04
  tags:
  - site5
  x: 0.88
  y: 2.757
  yaw: -1.577
- id: node_05
  tags:
  - site0
  x: 0.326
  y: 0.485
  yaw: -0.006
